### ISSUE TITLE
Compilation error OSX10.8

### ISSUE THREAD

**Issue by EricOBoyer** [monkeyswarm/MobMuPlat#1]
Hi
I tried to compile MobMuPlat on OSX10.8, and I got the following error:

if ([locationManager respondsToSelector:@selector(requestWhenInUseAuthorization)]) {
          [locationManager requestWhenInUseAuthorization];
        }

error -> No visible @interface for 'CLLocationManager' declares the selector 'requestWhenInUseAuthorization'

Any idea how to fix this?
Thanks

Eric

**Comment by monkeyswarm** [comment]
What is your
1) Version of XCode
2) iOS SDK target
?

**Comment by EricOBoyer** [comment]
Hi
I run Xcode 5.1.1 on OSX 10.8
The target was iPhone Retina 4inch

FYI, I commented these two lines and the compilation was ok (as well as
using the app so far).

Eric

2015-06-10 17:21 GMT+02:00 Daniel Iglesia <notifications@github.com>:

**Comment by monkeyswarm** [comment]
Should be fixed now. Reopen if not.
