### ISSUE TITLE
Build Error in Android Studio

### ISSUE THREAD

**Issue by uraltermann** [monkeyswarm/MobMuPlat#11]
Hi,

I'm trying to rebuild the Android App but i get an Error saying: Gradle 'MobMuPlat - Android' project refresh failed.
Error: Configuration with name 'default' not found.

Is there any solution?

**Comment by monkeyswarm** [comment]
Repo was missing a bunch of new files (in the "mobmuplatandroidwear" folder) which I just added. Please try again and let me know.

**Comment by uraltermann** [comment]
Now it works. Thank you!

2016-04-11 16:00 GMT+01:00 Daniel Iglesia <notifications@github.com>:

> Repo was missing a bunch of new files (in the "mobmuplatandroidwear"
> folder) which I just added. Please try again and let me know.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/monkeyswarm/MobMuPlat/issues/11#issuecomment-208387154>
>



-- 
______________
Maurits Boettger
Venloer Straße 28
50672 Köln
Mobil +49 157 8784 4876
Tel +49 221 1685 4146
