### ISSUE TITLE
slider range

### ISSUE THREAD

**Issue by umlaeute** [monkeyswarm/MobMuPlat#12]
1. i wonder why a slider-range `2` means `0<=float<=1` (that is: why isn't this the behaviour of slider-range `1`)

2. why can't I create a integer-slider that switches between two values `0` and `1`?
  - functionality-wise this is equivalent to a toggle (but with a different GUI semantic)
  - it would also be the logical behaviour for a slider-range `2`

**Comment by monkeyswarm** [comment]
Changed in iOS 1.80 and Android .30, and their respective editors. Knobs/Sliders with a range of "1" now are 0-1 float, with range "2" 0 and 1 integer.

Note that older patches should still work correctly in a legacy mode. MMP files have a "version" that protects against breaking changes. This functionality change updates that version to "2", (and anytime you save an editor patch with newer editors it will update that value). Patches will respond to mmp version < 2 (old behavior) and >=2 (new behavior).
