### ISSUE TITLE
switch on landini from within pd

### ISSUE THREAD

**Issue by hwkcgn** [monkeyswarm/MobMuPlat#17]
in some situations it would be very helpful to be able to switch on landini from within a pd patch via a message.
e.g. when distributing a patch to volunteer performers it would be one step less to set up properly.

**Comment by monkeyswarm** [comment]
Added in iOS 1.80 and Android .30
See mobmuplat.com/doc, under "networking". Basically, send a 
list landini/enable 1 
or
list pingandconnect/enable 1 
to turn them on programatically.
