### ISSUE TITLE
Make GPS work in background

### ISSUE THREAD

**Issue by mxa** [monkeyswarm/MobMuPlat#2]
Currently MobMuPlat can continue to process audio even while the screen is turned off (setting in audio and MIDI preferences). Sensor input like gyro and compass also keep working. GPS position however is not updated once the screen is turned off.
It would be great to have this feature, so one can concentrate on the auditive experience while on a GPS based audio walk.

**Comment by mxa** [comment]
Maybe this is a starting point? https://stackoverflow.com/questions/7387294/run-gps-listener-in-background-android

**Comment by monkeyswarm** [comment]
When I turn on that setting ("Audio runs while app is in background"), GPS updates continue to be received and processed by the PD patch while MobMuPlat is in the background and/or the screen is turned off. I am running stock android 5.1.

Either your device settings are blocking backgrounded apps from using location data, or your manufacturer's flavor of Android has interfered with this behavior. What type of device (and version) are you using?

**Comment by mxa** [comment]
That's interesting. I am on Android 4.4.4 in the form of cyanogenmod 11 on a Sony Xperia V. I'm planning to upgrade to cm12 soon, will report back if  it works there.

**Comment by monkeyswarm** [comment]
CyanogenMod handles GPS-in-background differently than stock Android. Perhaps there is a system setting somewhere that will enable it. Closing, as I am not planning on adding CM-specific workarounds.
