### ISSUE TITLE
mobmuplat <> pd: port in use error

### ISSUE THREAD

**Issue by batchku** [monkeyswarm/MobMuPlat#22]
I intermittently have this issue with the latest editor and pd 0.47.1 where i can't get the GUI (running in the editor, on my mac) to talk to PD.  PD can send numbers to the GUI (running in the editor) but not the other way.  I get this error when i open the PdWrapper patch:

```
bind: Address already in use (48)

connecting to port 54310
connecting to port 54321
bind: Address already in use (48)
```

I get this error even if i quit both pd and the mobmuplat editor; and then launch one after another.  

Restarting the computer does the trick.  

Somehow, somebody is holding on to a network port and not letting it go.

hmmm?

**Comment by korakios** [comment]
On a PC there is also no communication. I first launch _"LaunchPureDataAndPdWrapperFromWindows.bat"_ and loading a patch has no connection. If I click on the connect object on PdWrapper it says 'already connected'.
The trick/workaround is to close the patch and reload it. (leaving PdWrapper and the editor opened) 
Then, I click again to connect from PdWrapper ,and it works.

**Comment by monkeyswarm** [comment]
Yes, that means some other process is hanging on to that port (either a hung/crashed PD process, or something active that just happens to use the same port)
You can find it and kill it, e.g.
http://stackoverflow.com/questions/3855127/find-and-kill-process-locking-port-3000-on-mac
