### ISSUE TITLE
more gracefully handle non-list messages to special receivers

### ISSUE THREAD

**Issue by umlaeute** [monkeyswarm/MobMuPlat#25]
currently all the `toXXX` receivers require `list` messages (and the `fromXXX` will emit `list` messages as well).
since Pd`s `[route]` doesn't like lists but instead uses the *selector*, this boils down that virtually every communication with the MobMuPlat fromawork requires an explicit `[list trim]` (to get rid of the "list" selector when receiving data) or an explicit `[list]` (to add that "list" selector before sending data).

schouldn't this be incorporated into MobMoPlat itself?

**Comment by monkeyswarm** [comment]
The communication between the native app layer and the patch (via libpd) uses a list. So there's no way to strip it off in the app layer. Even if there were, it seems counterintuitive to mangle an incoming list, when a simple [list trim] does what is desired.
