### ISSUE TITLE
iOS: Sampling rate always at 48kHz

### ISSUE THREAD

**Issue by mxa** [monkeyswarm/MobMuPlat#27]
on someone's iOS device I saw the behaviour that the sampling rate is not settable. When selecting one of the other rates, the switch always goes back to 48kHz after a few ms.

**Comment by monkeyswarm** [comment]
Newer models of iPhones do not have variable sampling rate for the on-device speaker output. It is always fixed at 48k. If someone plugs in an audio cable to the headphone jack, that audio output may or may not have a variable sample rate.
