### ISSUE TITLE
Feature Request : Audio Unit (AU)

### ISSUE THREAD

**Issue by korakios** [monkeyswarm/MobMuPlat#30]
It would be great (if possible) making MobMuPlat launch as Audio Unit plugin.
This way we can load several instances of pure data patches.

**Comment by monkeyswarm** [comment]
What do you mean "launch as Audio Unit plugin"? Is this for a DAW (on mobile devices vs non-mobile devices)?

**Comment by korakios** [comment]
Yes , it's for DAWs in iOS like Cubasis, Auria , or Audiobus3 and AUM . The benefit over IAA ( inter app audio) is multiple instances . But I am not a developer, so I don't know the amount of work or even possible. It's just a feature request :)

**Comment by korakios** [comment]
Closing it as it will require much work and maybe it’s better focusing to simpler things :)
