### ISSUE TITLE
LANpidin in puredata patch

### ISSUE THREAD

**Issue by giulianobici** [monkeyswarm/MobMuPlat#37]
Hi all , 
Experimenting the great LANdini to control multiple cellphones in a local network. It's running  great. 

Does have any possibility to run LANdini from PD in a laptop (linux or osx) to send message to the network?

Best.

**Comment by monkeyswarm** [comment]
See the LANdini author's page for Supercollider code that will run as a LANdini client on a laptop/desktop. 
http://www.jaschanarveson.com/pages/code.html
