### ISSUE TITLE
mobmuplat.com webpage down ?

### ISSUE THREAD

**Issue by phae-ilias** [monkeyswarm/MobMuPlat#4]
Hello,

I wanted to go to the MobMuPlat website to get the MobMuPlat editor and read instructions...
but I get a 404 Error, with a banner from "The Music Departement / Columbia University"
Is it just me ? and I can't find how to get the MobMuPlat editor from github...

thanks,

**Comment by phae-ilias** [comment]
seems to be back online now...

**Comment by monkeyswarm** [comment]
Yup, thanks for pointing it out, I was able to get the page back up...
