### ISSUE TITLE
GUI size is not always scaled (and a suggestion)

### ISSUE THREAD

**Issue by MarioMey** [monkeyswarm/MobMuPlat#49]
My tablet screen is 1280x800. I use "tallTablet" for my interface. At first time I open it, it is scaled to screen size (theres black empty spaces at sides)
![screenshot_2018-03-25-13-37-27](https://user-images.githubusercontent.com/4954109/43360817-6542245e-9295-11e8-814f-373a85c40e3e.png)

 Second time I open my file, it is not scaled. Now, wasted space is not only at sides, but top and bottom.
![screenshot_2018-07-28-18-39-22](https://user-images.githubusercontent.com/4954109/43360801-c05ff4e8-9294-11e8-8cc0-526a6fab68e1.png)

Suggestion: custom GUI size. To take advantage of all screen size.
Bug: open file at second time, it is not scaled.

**Comment by korakios** [comment]
+1
Also it's painful to set properly the dimensions in native PD environment and have to be precise on saving the patch to proper window size.
I'd suggest placing a canvas (labeled with an exclusive name such as GUIscreen) on both MobMuPlat and native GUI,  that defines the resolution.  A user will place the objects easily inside that canvas without having to worry about scaling issues or at least test easily on each device

**Comment by monkeyswarm** [comment]
What device and OS version is this?

**Comment by MarioMey** [comment]
Samsung Galaxy 2 10', Android 4.0, I think. Maybe 4.1...

If you really need to know it, I have to charge device and turn it on. Tell me.

**Comment by monkeyswarm** [comment]
4.0 and 4.1 have both been unsupported (by Google) for more than a year, so this is outside of my control.

**Comment by MarioMey** [comment]
Ok.
