### ISSUE TITLE
midi question

### ISSUE THREAD

**Issue by badgeek** [monkeyswarm/MobMuPlat#5]
is it possible to use ctlin pd object to get midi output?

**Comment by monkeyswarm** [comment]
Yes. Is it not working for you?

**Comment by badgeek** [comment]
usually i got dialog asking for usb permission in android, for example grand piano app and usb midi monitor app the dialog does not appear.

**Comment by monkeyswarm** [comment]
Go to the Audio + MIDI settings and hit "refresh MIDI devices". You should get the permission dialog at that point.
