### ISSUE TITLE
Error keycode 92: dropped ....  can't update mmp gui because of "\" not allowed in puredata anymore.

### ISSUE THREAD

**Issue by stillpointx** [monkeyswarm/MobMuPlat#59]
When I try to send toGUI  using a message box using `"list /myLabel \$1"`  to update the GUI on my local PC I get a error in Pd **keycode 92: dropped**.  Due to a change in PureData see link https://sourceforge.net/p/pure-data/bugs/1159/

I can't update the mmp gui on the desktop because the type of backslash `"\"` which MobMuPlat uses is not allowed in puredata any-more they are automatically dropped.

Is their a workaround?  I'm using Pd 0.48.1 on ubuntu 18.04 64bit I'lve attached the two files 

[test_files.zip](https://github.com/monkeyswarm/MobMuPlat/files/2838062/test_files.zip)

**Comment by monkeyswarm** [comment]
What is the purpose of sending a string message with a backslash to a GUI element? Are you trying to escape the dollar sign so that the label literally shows '$1' in it?

**Comment by stillpointx** [comment]
I was trying to get the label boxes to update when updating the MobMuPlat Java GUI sliders.  The Label boxes updates when using the tablet but when using the sliders in the MobMuPlat Java GUI on the PC the sliders won't update the "label boxes"

**Comment by monkeyswarm** [comment]
Just send a message without a backslash
list /myLabel $1 
or send a message to an object:
list prepend /myLabel

**Comment by stillpointx** [comment]
Thanks :-)
