### ISSUE TITLE
Suggestion/request: "local feedback" option in Toggles.

### ISSUE THREAD

**Issue by MarioMey** [monkeyswarm/MobMuPlat#9]
Toggle buttons should have "Local feedback" option (that TOSC has)... that makes the toggle not to change when tapped, but when it receive a "set 1" message. Because if the message that send to computer is lost in space and it never arrives to Pd (for example), in the interface, toggle would be on, but, in Pd, off.

(I know that the idea of MobMuPlat is not to be the same as TouchOSC... but there're some stuff that I would want MMP to have...)

**Comment by monkeyswarm** [comment]
You can create this behavior in the Pd patch, without needing to change any functionality of the GUI layer. 

![screen shot 2016-01-29 at 9 11 12 am](https://cloud.githubusercontent.com/assets/1235083/12682439/4914c8aa-c668-11e5-897a-c09e4b3e214d.png)

**Comment by MarioMey** [comment]
Ok, thanks!
