### ISSUE TITLE
How to start the troubleshooting 

### ISSUE THREAD

**Issue by ManosDim** [monkeyswarm/MobMuPlat#90]
![355625211_647289266984661_5694620357469696093_n](https://github.com/monkeyswarm/MobMuPlat/assets/48352514/3db223ed-1917-4e87-b828-1c40a50086b6)
![356792732_650479783792745_1855775180410210598_n](https://github.com/monkeyswarm/MobMuPlat/assets/48352514/e94747f5-30aa-4dee-987e-f0663cdf0d6f)
Hey ppl, I have these weird errors in the PD console and I don't really know how to start troubleshooting. The app works fine on the PC, but when I tried it on the iPad. It doesn't really respond, and I tried to see if it was a midi connection by making a very simple app to display the incoming midi notes, but it wasn't. Do you have any ideas on how I could start troubleshooting? 
Thanks! =)

**Comment by monkeyswarm** [comment]
This is usually due to a version mismatch between what MobMuPlat/libpd supports, and the desktop version of Pd you've used to make the patch. (i.e. missing objects). I'm guessing the very start of the log has a 'missing object XXX' error.

**Comment by ManosDim** [comment]
![356192479_1360559594879813_5563548314190223965_n](https://github.com/monkeyswarm/MobMuPlat/assets/48352514/6ba09ea1-8498-4b45-920b-78292ede3c8d)
That is the very first message. I'm using Pd version 0.52.2, in the documentation says that i need 0.46 and above, so I should be fine, right?

**Comment by monkeyswarm** [comment]
It's the other way around; the current iOS version only supports up 0.46 (It might have been updated to 0.47 or 0.48, I forget). Newer versions of Pd will not work because they will contain objects which don't exist in the older version. You'll have to test your patch on an older version of Pd. 
I admit that the iOS version could use an upgrade. Android was recently upgraded to support up to Pd 0.51.

**Comment by ManosDim** [comment]
I jumped to iOS because I couldn't connect midi devices in the android version of MobMuPlat. Do you have any fixes for this one? I'm using a BLE MIDI device and I can connect it and send midi notes in other Android apps but in MobMuPlat in i can't, although in the iPad works fine
